---
title: "R Notebook"
output: html_notebook
---

INTRO

Importamos las librerías a utilizar

```{r}
rm(list=ls())

require(dplyr)
require(ggplot2)
require(tsibble)
require(lubridate)
require(prophet)
require(forecast)
```


Importamos los datasets con los que se va a trabajar:

```{r}
df_abc <- read.csv("./datasets/202208_PAX15min-ABC.csv", sep=";")
df_deh <- read.csv("./datasets/202208_PAX15min-DEH.csv", sep=";")

df <- bind_rows(df_abc, df_deh)
rm(df_abc, df_deh)
```

Agrupamos la información a nivel estación/horario y convertimos a formato fecha/hora:

```{r}
df = df %>%
  group_by(FECHA, DESDE, HASTA, LINEA, ESTACION) %>%  # evaluar agrupar a nivel linea y quedarse con una única línea para el análisis
  summarize(pasajeros = sum(pax_TOTAL)) %>%
  mutate(ts = dmy_hms(paste0(FECHA," " ,DESDE))) %>%
  ungroup() %>%
  select(-c(FECHA, DESDE, HASTA))  ## ver si dejar esto o no
```


Agrupamos por linea y observamos la cantidad de pasajeros para cada una de ellas:

```{r}
df %>%
  filter(ts >= "2022-08-01 05:15:00" & ts <= "2022-08-07 23:15:00") %>%
  group_by(LINEA, ts) %>%
  summarise(pasajeros = sum(pasajeros)) %>%
  ggplot() +
  aes(x = ts, y = pasajeros, fill = LINEA, colour = LINEA, group = LINEA) +
  geom_line(size = 0.5) +
  scale_fill_manual(values = c(LineaA = "#5CD2FB", LineaB = "#FD2929", LineaC = "#1872D6", LineaD = "#39A029", LineaE = "#583FD2", LineaH = "#FFEC3B")) +
  scale_color_manual(values = c(LineaA = "#5CD2FB", LineaB = "#FD2929", LineaC = "#1872D6", LineaD = "#39A029", LineaE = "#583FD2", LineaH = "#FFEC3B")) +
  labs(x = "horario del día", y = "cantidad de pasajeros", title = "cantidad de pasajeros por linea") + 
  theme_linedraw() +
  theme(legend.position = "none") +
  facet_wrap(vars(LINEA)) + 
  scale_x_datetime(breaks= seq(min(df$ts), max(df$ts), by = "24 hour"), date_labels = "%a %H %M") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```


Para el análisis, nos  vamos a quedar con la información de la linea X para el período Y:
```{r}
df %>%
  filter(LINEA == 'LineaD') %>%
  group_by(LINEA,ts) %>%
  summarise(pasajeros = sum(pasajeros)) %>%
  ggplot(aes(x = ts, y=pasajeros)) +
  geom_line(colour = "#39A029") +
  labs(x = "horario del día", y = "cantidad de pasajeros", title = "cantidad de pasajeros de la linea D") + 
  theme_linedraw() +
  theme(legend.position = "none") + 
  scale_x_datetime(breaks= seq(min(df$ts), max(df$ts), by = "12 hour"), date_labels = "%a %H %M") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 5))


```
prophet

```{r}
df_lineaD = df %>%
  filter(LINEA == 'LineaD') %>%
  group_by(LINEA,ts) %>%
  summarise(pasajeros = sum(pasajeros)) %>%
  ungroup() %>%
  select(ts, pasajeros) %>%
  rename(ds = ts, y = pasajeros)

```



```{r}
# Feriados
feriados = data.frame(
  holiday= 'feriados',
  ds= ymd(c('2022-08-15','2022-10-07','2022-10-10')),
  lower_window= 0,
  upper_window= 0)

```


```{r}
# Llamamos al modelo con el dataset de eventos
prophet_full=prophet(changepoint.prior.scale=0.01, holidays = feriados)

# Agregamos la estacionalidad mensual
#prophet_full=add_seasonality(prophet_full, name='monthly', period=30.5, fourier.order = 4)

# Le pasamos el dataset
prophet_full = fit.prophet(m = prophet_full, df_lineaD) 
```

```{r}
prophet_plot_components(prophet_full, fcst=predict(prophet_full, df_lineaD))
```

